before_script:
  - npm update
  - bower update --allow-root

protractor:
  script:
    - cd ./app
    - http-server -p 8080 > ../http.log &
    - cd ../
    - service xvfb start
    - run-selenium
    - sleep 1
    - protractor ./e2e/protractor.conf.js
    - service xvfb stop
  tags:
    - plain
    - node
    - karma
    - protractor