before_script:
  - npm set registry http://npm-cache:4873
  - npm install --silent
  - ./node_modules/.bin/bower install --allow-root

protractor:
  script:
    - cd ./app
    - ../node_modules/.bin/http-server -p 8080 --silent &
    - cd ../
    - service xvfb start
    - run-selenium
    - sleep 5
    - ./node_modules/.bin/protractor ./e2e/protractor.conf.js
    - service xvfb stop
  tags:
    - plain
    - node
    - xvfb
    - selenium
    - chrome

karma:
  script:
    - service xvfb start
    - run-selenium
    - sleep 5
    - node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run
    - service xvfb stop
  tags:
    - plain
    - node
    - xvfb
    - selenium
    - chrome