before_script:
  - npm update

protractor:
  script:
    - bower update --allow-root
    - cd ./app
    - http-server -p8080 > ../http.log &
    - cat ../http.log
    - cd ../
    - /etc/init.d/xvfb start
    - java -jar /opt/selenium/selenium-server-standalone.jar > selenium.log &
    - sleep 1
    - protractor ./e2e/protractor.conf.js
    - /etc/init.d/xvfb stop
  tags:
    - plain
    - node
    - karma
    - protractor