before_script:
  - npm update

protractor:
  script:
    - cd ./app
    - http-server -p8080 > /dev/null 2>&1 &
    - cd ../
    - /etc/init.d/xvfb start
    - sleep 1
    - protractor ./e2e/protractor.conf.js --browser=chrome
    - /etc/init.d/xvfb stop
  tags:
    - plain
    - node
    - karma
    - protractor