before_script:
  - npm update
  - webdriver-manager update
  - webdriver-manager start > /dev/null 2>&1 &
  - sleep 1

test:
  script:
    - cd ./app
    - http-server -p8080 > /dev/null 2>&1 &
    - sleep 1
    - cd ../
    - protractor ./e2e/protractor.conf.js --browser=firefox
  tags:
    - node
    - karma
    - protractor
    - httpserver