before_script:
  - npm update

test:
  script:
    - karma start karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
    - protractor e2e-tests/protractor.conf.js --browser=firefox
  tags:
    - node
    - karma
    - protractor
    - selenium
    - firefox