docker:
  script:
    - npm install --silent bower
    - ./node_modules/.bin/bower install --quiet --allow-root
    - docker build -q -t ankoh/mc-client .
  tags:
    - docker
    - node
  only:
    - master
    - testing

github:
  type: deploy
  script:
    - mkdir -p ~/.ssh/
    - echo "$GITHUB_DEPLOYMENT_KEY" > ~/.ssh/github.key
    - printf "Host github\n    HostName github.com\n    User git\n    IdentityFile ~/.ssh/github.key\n" >> ~/.ssh/config
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - chmod 700 ~/.ssh/
    - chmod 600 ~/.ssh/config
    - chmod 600 ~/.ssh/github.key
    - chmod 600 ~/.ssh/known_hosts
    - git push --all ssh://github/ankoh/mc-client.git

compose-dockerbruegge1:
  type: deploy
  script:
    - npm install --silent bower
    - ./node_modules/.bin/bower install --quiet --allow-root
    - sed -i'' -e s%:mchost%https://dockerbruegge1.informatik.tu-muenchen.de% -e s/:mcport/22760/ -e s/:port/32761/ compose.yml
    - mkdir -p ~/.ssh/
    - echo "$DOCKERBRUEGGE_DEPLOYMENT_KEY" > ~/.ssh/dockerbruegge1.key
    - printf "Host dockerbruegge1\n    HostName dockerbruegge1.informatik.tu-muenchen.de\n    User itg\n    IdentityFile ~/.ssh/dockerbruegge1.key\n" >> ~/.ssh/config
    - ssh-keyscan dockerbruegge1.informatik.tu-muenchen.de >> ~/.ssh/known_hosts
    - chmod 700 ~/.ssh/
    - chmod 600 ~/.ssh/config
    - chmod 600 ~/.ssh/dockerbruegge1.key
    - chmod 600 ~/.ssh/known_hosts
    - ssh dockerbruegge1 "mkdir -p ~/projects/mendeley-cache/client;
        rm -rf ~/projects/mendeley-cache/client;
        mkdir -p ~/projects/mendeley-cache/client;"
    - tar -czf client.tar.gz app docker compose.yml Dockerfile
    - scp client.tar.gz dockerbruegge1:~/projects/mendeley-cache/client/
    - ssh dockerbruegge1 "tar -xzf ~/projects/mendeley-cache/client/client.tar.gz -C ~/projects/mendeley-cache/client"
    - ssh dockerbruegge1 "cd ~/projects/mendeley-cache/client;
        docker build -t ankoh/mc-client .;
        docker-compose -f compose.yml -p mcclient stop;
        docker-compose -f compose.yml -p mcclient up -d;
        rm -rf ~/projects/mendeley-cache/client;
        docker rmi \$(docker images | grep '<none>' | awk '{print $3}') 2>/dev/null || echo 'No untagged images to delete.'"
  only:
    - master
