# protractor:
#   script:
#     - cd ./app
#     - ../node_modules/.bin/http-server -p 8080 --silent &
#     - cd ../
#     - service xvfb start
#     - run-selenium
#     - sleep 5
#     - ./node_modules/.bin/protractor ./e2e/protractor.conf.js
#     - service xvfb stop
#   tags:
#     - plain
#     - node
#     - xvfb
#     - selenium
#     - chrome

# karma:
#   script:
#     - service xvfb start
#     - run-selenium
#     - sleep 5
#     - node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run
#     - service xvfb stop
#   tags:
#     - plain
#     - node
#     - xvfb
#     - selenium
#     - chrome

docker:
  script:
    - npm set registry http://npm-cache:4873
    - npm install --silent bower
    - ./node_modules/.bin/bower install --quiet --allow-root
    - docker build -q -t ankoh/mendeleycache-client .
  tags:
    - docker
    - node
  only:
    - master

compose-local:
  type: deploy
  script:
    - docker-compose -f compose.yml -p mcclient stop
    - docker-compose -f compose.yml -p mcclient rm -vf
    - docker-compose -f compose.yml -p mcclient up -d
  tags:
    - privileged
  only:
    - master

github:
  script:
    - mkdir -p ~/.ssh/
    - echo "$GITHUB_DEPLOYMENT_KEY" > ~/.ssh/github.key
    - printf "Host github\n    HostName github.com\n    User git\n    IdentityFile ~/.ssh/github.key\n" >> ~/.ssh/config
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - chmod 700 ~/.ssh/
    - chmod 600 ~/.ssh/config
    - chmod 600 ~/.ssh/github.key 
    - chmod 600 ~/.ssh/known_hosts
    - git push --all ssh://github/ankoh/mendeley-cache-client.git